- name: Create Application User
  import_role:
    name: os-configs
    tasks_from: appuser

- name: Install Java
  yum:
    name: java
    state: latest

- name: Download artifacts from Nexus
  import_role:
    name: os-configs
    tasks_from: download-latest.yml

- name: Copy the artifacts
  get_url:
    url: "{{latest.stdout}}"
    dest: "{{APPLICATION_HOME}}/shipping.jar"
    mode: '0755'
  become_user: "{{APPLICATION_USERNAME}}"

- name: Start the Service
  import_role:
    name: os-configs
    tasks_from: systemd.yml
  vars:
    COMMAND: /usr/bin/nohup java -jar {{APPLICATION_HOME}}/shipping.jar

