- name: Set up Roboshop application
  hosts: all
  become: yes
  tasks:
    - name: Import User component
      import_role:
        name: user
      tags:
        - user
    - name: Import Catalogue component
      import_role:
        name: catalogue
      tags:
        - catalogue
    - name: Import cart component
      import_role:
        name: cart
      tags:
        - cart
    - name: Import Dispatch component
      import_role:
        name: dispatch
      tags:
        - dispatch
    - name: Import Shipping Component
      import_role:
        name: shipping
      tags:
        - shipping
    - name: Import Payment Component
      import_role:
        name: payment
      tags:
        - payment
