- name: Setup User Application
  import_role:
    name: nodejs-app
  vars:
    DOWNLOAD_LATEST: true
    APPLICATION_NAME: user

- name: Set up application dependencies
  include_role:
    name: os-configs
    tasks_from: system-dependencies
  vars:
    VARIABLE: "{{item}}"
    APPLICATION_NAME: user
  loop:
      - MONGO_URL
      - REDIS_HOST