- name: Create Application user and directory
  import_role:
    name: os-configs
    tasks_from: appuser

- name: Install Python packages
  package:
    name: "{{item}}"
    state: present
  loop:
    - python36
    - gcc
    - python3-devel

- name: Download artifacts from Nexus
  import_role:
    name: os-configs
    tasks_from: download-latest.yml

- name: Copy Artifacts to Directory
  unarchive:
    src: "{{latest.stdout}}"
    dest: "{{APPLICATION_HOME}}"
    remote_src: yes