- name: Create Application user and directory
  import_role:
    name: os-configs
    tasks_from: appuser

- name: Install Python packages
  package:
    name: "{{item}}"
    state: present
  loop:
    - python36
    - gcc
    - python3-devel

- name: Download artifacts from Nexus
  import_role:
    name: os-configs
    tasks_from: download-latest.yml

- name: Copy Artifacts to Directory
  unarchive:
    src: "{{latest.stdout}}"
    dest: "{{APPLICATION_HOME}}"
    remote_src: yes

- pip:
    requirements: requirements.txt
    executable: pip3

- name: Copy the {{APPLICATION_NAME}}.service file to system location
  template:
    src: systemd
    dest: /etc/systemd/system/{{APPLICATION_NAME}}.service

- name: Systemd Daemon-reload
  systemd:
    daemon_reload: yes

- name: Create a log directory
  file:
    path: /var/log/{{APPLICATION_USERNAME}}
    state: directory

- name: Restart Service
  systemd:
    name: "{{APPLICATION_NAME}}"
    state: restarted
    enabled: yes


