- name: Curl a nodejs webpage
  shell: curl -s https://nodejs.org/en/download/ | xargs -n1 | grep linux-x64.tar | sed -e 's|=| |g' -e 's|>| |g'| xargs -n1 | grep ^http
  register: out

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{out.stdout}}"
    dest: /opt
    remote_src: yes