- name: Set up catalogue application
  import_role:
    name: nodejs-app
  vars:
    DOWNLOAD_LATEST: true
    APPLICATION_NAME: catalogue

- name: Set up application dependencies
  include_role:
    name: os-configs
    tasks_from: system-dependencies
  vars:
    VARIABLE: {{item}}
    APPLICATION_NAME: catalogue
    - loop:
        - MONGO_URL

