- name: install the latest version of Apache
  yum:
    name: "{{item}}"
    state: installed
  loop:
    - httpd
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - yum-utils

- name: Install PHP
  yum:
    name: "{{item}}"
    state: installed
    enablerepo: "remi-php73"
  loop:
    - php
    - php-opcache
    - php73-php-pdo
    - composer


- name: Change the line
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    line: Listen 7004
