- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
  loop:
    - httpd
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - yum-utils

- name: Add repository
  yum_repository:
    name: remi-php73
    enabled: yes

- name: Install Python packages
  yum:
    name: "{{item}}"
    state: present
  loop:
    - php
    - php-opcache
    - php73-php-pdo
    - composer