filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - {{LOG_NAME}}
    fields:
      appname: {{FIELD_NAME}}

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["172.31.20.249:5044"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
