- name: Create Application User
  user:
    name: "{{APPLICATION_USERNAME}}"

- name: Create Directory
  file:
    path: "{{APPLICATION_HOME}}"
    state: directory
    owner: "{{APPLICATION_USERNAME}}"
    group: "{{APPLICATION_USERNAME}}"

- name: Setup Latest  APP
  when: DOWNLOAD_LATEST
  import_tasks: download-latest.yml
  become_user: "{{APPLICATION_USERNAME}}"

- name: Setup Systemd Service
  import_tasks: systemd.yml




